mppi:
  T: 30
  K: 500
  lambda: 1.0 # this is the temperature parameter higher = more exploration, lower = more exploitation
  alpha: 0.1 # control cost weight, higher = less control effort, lower = more control effort
  exploration: 0.1 # fraction of rollouts using nominal control
  delta_t: 0.02
  dim_x: 6
  dim_u: 3

seed: 42

noise:
  sigma:
    - [9, 0.0, 0.0] # linear x
    - [0.0, 9, 0.0] # linear y
    - [0.0, 0.0, 4] # angular

map:
  x_limits: [-10.0, 10.0]
  y_limits: [-10.0, 10.0]
  resolution: 0.2
  oom_cost: 100.0

obstacles:
  num_obstacles: 8
  min_radius: 0.5
  max_radius: 1.5
  x_limits: [-8.0, 8.0]
  y_limits: [-8.0, 8.0]
  weight: 100.0
  safe_distance: 0.2

gmm2d:
  weights:
    - 0.5
    - 0.3
    - 0.2
  means:
    - [-2.5, -3.8]
    - [5.0, -2.5]
    - [3.5, 3.5]
  covariances:
    - [[4.0,  2.0], [2.0,  4.0]]
    - [[3.0, -1.5], [-1.5, 3.0]]
    - [[4.0,  0.0], [0.0,  2.0]]
  drift:
    sigma: 1.0
    S: [[0.0, -1.0], [1.0, 0.0]]

stein:
  weight: 1.0
  weight_pdf: 3.0
  h: 1.0
  gamma: 0.5

model:
  delta_t: 0.02
  double_integrator:
    max_accel_lin_abs: 20.0 # m/s²
    max_accel_ang_abs: 20.0 # rad/s²